# coding: utf-8

"""
    CloudCheckr API

    CloudCheckr API  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@cloudcheckr.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudcheckr_cmx
from cloudcheckr_cmx.models.create_request_client_access_key_request_model import CreateRequestClientAccessKeyRequestModel  # noqa: E501
from cloudcheckr_cmx.rest import ApiException


class TestCreateRequestClientAccessKeyRequestModel(unittest.TestCase):
    """CreateRequestClientAccessKeyRequestModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateRequestClientAccessKeyRequestModel(self):
        """Test CreateRequestClientAccessKeyRequestModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudcheckr_cmx.models.create_request_client_access_key_request_model.CreateRequestClientAccessKeyRequestModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
