# coding: utf-8

"""
    Pulp 3 API

    Fetch, Upload, Organize, and Distribute Software Packages  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: pulp-list@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulp_maven
from pulpcore.client.pulp_maven.api.distributions_maven_api import DistributionsMavenApi  # noqa: E501
from pulpcore.client.pulp_maven.rest import ApiException


class TestDistributionsMavenApi(unittest.TestCase):
    """DistributionsMavenApi unit test stubs"""

    def setUp(self):
        self.api = pulpcore.client.pulp_maven.api.distributions_maven_api.DistributionsMavenApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create2(self):
        """Test case for create2

        Create a maven distribution  # noqa: E501
        """
        pass

    def test_delete(self):
        """Test case for delete

        Delete a maven distribution  # noqa: E501
        """
        pass

    def test_list2(self):
        """Test case for list2

        List maven distributions  # noqa: E501
        """
        pass

    def test_partial_update(self):
        """Test case for partial_update

        Update a maven distribution  # noqa: E501
        """
        pass

    def test_read2(self):
        """Test case for read2

        Inspect a maven distribution  # noqa: E501
        """
        pass

    def test_update(self):
        """Test case for update

        Update a maven distribution  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
