ELECTORAL_COLLEGE_BODY = "electoral_college"
US_SENATE_BODY = "senate"
US_HOUSE_BODY = "house"
STATE_GOVERNORS_BODY = "governor"

ACCEPTED_GOVERNMENT_BODIES = [
    ELECTORAL_COLLEGE_BODY,
    US_SENATE_BODY,
    US_HOUSE_BODY,
    STATE_GOVERNORS_BODY,
]


SOLID_DEM_CATEGORY = "Solid-D"
LIKELY_DEM_CATEGORY = "Likely-D"
LEAN_DEM_CATEGORY = "Lean-D"
TOSS_UP_CATEGORY = "Toss-Up"
LEAN_GOP_CATEGORY = "Lean-R"
LIKELY_GOP_CATEGORY = "Likely-R"
SOLID_GOP_CATEGORY = "Solid-R"

RATING_CATEGORIES = [
    SOLID_DEM_CATEGORY,
    LIKELY_DEM_CATEGORY,
    LEAN_DEM_CATEGORY,
    TOSS_UP_CATEGORY,
    LEAN_GOP_CATEGORY,
    LIKELY_GOP_CATEGORY,
    SOLID_GOP_CATEGORY,
]
