[tool.poetry]
name = "pyqt-sql-demo"
version = "1.0.0"
description = "PyQT SQL executor demo example using DB API (no QtSQL)"
authors = ["vduseev <vagiz@duseev.com>"]
license = "MIT"

[tool.poetry.scripts]
pyqt-sql-demo = "pyqt_sql_demo.app:launch"

[tool.poetry.dependencies]
python = "^3.8"
pyqt5 = "^5.15.0"
pygments = "^2.6.1"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
ipython = "^7.18.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
