-   id: scss-compile
    name: Compile SCSS
    description: This hook compiles SCSS to CSS.
    entry: scss-compile
    language: python
    language_version: python3
    require_serial: true
    types: [scss]
