
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-09T08:35:03+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "185b4599666a14b1ece9047f5941ac42c5360223",
 "version": "0.6.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
