[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4"]

[tool.setuptools_scm]

[tool.pylint.FORMAT]
max-line-length="88"

[tool.pylint."MESSAGES CONTROL"]
# bad-continuation: Black does the job, no need to check.
disable = "bad-continuation, logging-fstring-interpolation"

[tool.pylint.MASTER]
extension-pkg-whitelist="PyQt5"

[tool.pylint.TYPECHECK]
# zmq.{LINGER,REQ,ROUTER,NOBLOCK} are dynamically generated and so pylint
# doesn't see them, causing false positives.
generated-members="REQ,RCVTIMEO"