
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-14T18:45:08+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "fa77073b2e3611f851f7bf0f5bdc565a9aae4024",
 "version": "0.9.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
