[tool.poetry]
name = "ircparse"
version = "0.1.0"
description = "IRC parsing utilities"
authors = ["Andrew Herbig <notandrewherbig@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
pydantic = "^1.6.1"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.5.2"
pytest = "^6.0.2"
pre-commit = "^2.7.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
