# coding: utf-8

"""
    Robot API

    Robot REST API  # noqa: E501

    OpenAPI spec version: 1.8.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import aiopdhttp
from aiopdhttp.models.jogging_acceleration import JoggingAcceleration  # noqa: E501
from aiopdhttp.rest import ApiException


class TestJoggingAcceleration(unittest.TestCase):
    """JoggingAcceleration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJoggingAcceleration(self):
        """Test JoggingAcceleration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = aiopdhttp.models.jogging_acceleration.JoggingAcceleration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
