# coding: utf-8

"""
    Robot API

    Robot REST API  # noqa: E501

    OpenAPI spec version: 1.8.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pdhttp
from pdhttp.api.pose_api import PoseApi  # noqa: E501
from pdhttp.rest import ApiException


class TestPoseApi(unittest.TestCase):
    """PoseApi unit test stubs"""

    def setUp(self):
        self.api = pdhttp.api.pose_api.PoseApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_pose(self):
        """Test case for get_pose

        Getting the actual arm pose  # noqa: E501
        """
        pass

    def test_run_joint_poses(self):
        """Test case for run_joint_poses

        Asking the arm to follow the joint trajectory in Cartesian Space via waypoints represented in poses.  # noqa: E501
        """
        pass

    def test_run_linear_poses(self):
        """Test case for run_linear_poses

        Asking the arm to follow the linear trajectory in Cartesian Space via waypoints represented in poses  # noqa: E501
        """
        pass

    def test_run_poses(self):
        """Test case for run_poses

        Asking the arm to move to a pose  # noqa: E501
        """
        pass

    def test_set_pose(self):
        """Test case for set_pose

        Setting a new arm pose  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
