# coding: utf-8

"""
    Robot API

    Robot REST API  # noqa: E501

    OpenAPI spec version: 1.8.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pdhttp
from pdhttp.models.failure import Failure  # noqa: E501
from pdhttp.rest import ApiException


class TestFailure(unittest.TestCase):
    """Failure unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFailure(self):
        """Test Failure"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pdhttp.models.failure.Failure()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
