# coding: utf-8

"""
    Robot API

    Robot REST API  # noqa: E501

    OpenAPI spec version: 1.8.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pdhttp
from pdhttp.models.error_pose412 import ErrorPose412  # noqa: E501
from pdhttp.rest import ApiException


class TestErrorPose412(unittest.TestCase):
    """ErrorPose412 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorPose412(self):
        """Test ErrorPose412"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pdhttp.models.error_pose412.ErrorPose412()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
