
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-18T21:33:59-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "ecaf14097f5e69e5b884e9c87b708c85d181a9ef",
 "version": "2.27.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
