[tool.poetry]
name = "pywise"
version = "0.3.1"
description = "Robust serialization support for NamedTuple & @dataclass data types."
authors = ["Malcolm Greaves <greaves.malcolm@gmail.com>"]
homepage = "https://github.com/malcolmgreaves/pywise"
license = "Apache-2.0"
readme = 'README.md'
exclude = ['core_utils/support_for_testing.py'] # NEVER INCLUDE THIS FILE (!)
packages = [
    { include = "core_utils" },
]


[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.4.3"
mypy = "^0.782"
black = "^19.10b0"
flake8 = "^3.8.3"
ipython = "^7.15.0"
ipdb = "^0.13.3"
pyyaml = "^5.3.1"
tox = "^3.15.2"
numpy = "^1.19.0"
torch = "^1.5.1"
pytest-cov = "^2.10.0"
coveralls = "^2.0.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
