[tool.poetry]
name = "scrapysplashwrapper"
version = "1.2.4"
description = "Scrapy splash wrapper as a standalone library."
authors = ["Raphaël Vinot <raphael.vinot@circl.lu>"]
license = "BSD-3-Clause"
repository = "https://github.com/Lookyloo/ScrapySplashWrapper"
readme = "README.md"

classifiers=[
    'License :: OSI Approved :: BSD License',
    'Environment :: Console',
    'Intended Audience :: Science/Research',
    'Intended Audience :: Telecommunications Industry',
    'Programming Language :: Python :: 3',
    'Topic :: Security',
    'Topic :: Internet',
]

[tool.poetry.scripts]
scraper = "scrapysplashwrapper:main"

[tool.poetry.dependencies]
python = "^3.7"
scrapy = "^1.8.0"
scrapy-splash = "^0.7.2"

[tool.poetry.dev-dependencies]
mypy = "^0.782"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
