# Generated by Django 2.1.3 on 2018-11-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='size',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
