
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-16T09:32:13+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "01bcf2ab36f20d8f2ba65e4139343abcbe396068",
 "version": "0.4.1.post.dev16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
