[tool.poetry]
name = "arcane-google-analytics"
version = "0.3.0"
description = "A package to use Google Analytics API"
readme = "README.md"
authors = ["Arcane <product@arcane.run>"]
packages = [
    { include = "arcane" }
]

[tool.poetry.dependencies]
python = "^3.6"
arcane-core = "^1.0.3"
google-api-python-client = "1.7.8"
google-auth-httplib2 = "0.0.3"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
