[tool.poetry]
name = "mitxpro-openedx-extensions"
version = "0.2.1"
description = "MIT xPro plugins for Open edX"
authors = [
  "MIT Office of Open Learning <mitx-devops@mit.edu>"
]

keywords = [
]
classifiers = [
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.8"
]

packages = [
    { include = "mitxpro_core" },
]

[tool.poetry.plugins."lms.djangoapp"]
mitxpro_core = "mitxpro_core.apps:MITxProCoreConfig"

[tool.poetry.dependencies]
python = "~3.5 || ~3.8"
django = "~1.11.20"
futures = { version = "=3.2.0", python = "~2.7" }

[tool.poetry.dev-dependencies]
# Formatters
black = { version = "=18.9b0", python = "~3.8" }
isort = "=4.3.4"

# Linters
pylint = { version = "^2.0", python = "~3.5 || ~3.8" }
pylint-django = { version = "=2.3.0", python = "~3.8" }

# Testing
pytest = "^4.4"
pytest-cov = "*"
pytest-mock = "1.10.1"
pytest-django = "3.4.8"
pytest-lazy-fixture = "0.5.2"
codecov = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
