dist: xenial
language: generic
install: |
  wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh &&
  bash miniconda.sh -b -p $HOME/miniconda &&
  source "$HOME/miniconda/etc/profile.d/conda.sh" &&
  hash -r &&
  conda config --set always_yes yes &&
  conda update -q conda &&
  for pyver in $(python setup.py --classifiers | grep -Po 'Python :: \K.*'); do
    conda create -q -n "py$pyver" python="$pyver" &&
    conda activate "py$pyver" &&
    pip install --upgrade pip setuptools coverage &&
    pip install . &&
    conda deactivate ||
    exit 1
  done
script: |
  for env in $(conda info -e | grep -o '^py\S*'); do
    echo "Testing on $env" &&
    conda activate "$env" &&
    COVERAGE_FILE=".coverage.$env" python -mcoverage run --append --module unittest --buffer &&
    pip install docutils==0.10 sphinxcontrib-napoleon==0.7.0 &&  # Oldest supported versions.
    if [[ "$env" < py38 ]]; then
      pip install typing_extensions==3.7.4 typing_inspect==0.3.1  # Oldest supported versions.
    fi &&
    COVERAGE_FILE=".coverage.$env" python -mcoverage run --append --module unittest --buffer &&
    conda deactivate ||
    exit 1
  done &&
  conda activate "$env" &&
  python -mcoverage combine .coverage.* &&  # Unifies paths across envs.
  python -mcoverage report --show-missing
