__MAIN = "https://affilitest.com/"
LOGIN = __MAIN + "user/login"
LOGOUT = __MAIN + "user/logout"
TEST = __MAIN + "test"
COMPARE = __MAIN + "api/v1/compareToPreview"
APPINFO = __MAIN + "api/v1/appInfo"
CALLS_LEFT = __MAIN + "api/v1/callsLeft"
