
#########################################
# Edit the Docker Compose configuration #
# for the Meerschaum stack below        #
#########################################
networks:
  backend: null
  frontend: null
services:
  grafana:
    image: grafana/grafana:latest
    networks:
    - frontend
    - backend
    ports:
    - 3000:3000
    volumes:
    - grafana_storage:/var/lib/grafana
    - /home/bmeares/Meerschaum/src/meerschaum/config/stack/grafana/resources/provisioning/datasources:/etc/grafana/provisioning/datasources
    - /home/bmeares/Meerschaum/src/meerschaum/config/stack/grafana/resources/provisioning/dashboards:/etc/grafana/provisioning/dashboards
  meerschaum_api:
    command: api start
    depends_on:
    - meerschaum_db
    environment:
    - MEERSCHAUM_CONFIG=${MEERSCHAUM_API_CONFIG}
    hostname: meerschaum_api
    image: bmeares/meerschaum:latest
    networks:
    - frontend
    - backend
    ports:
    - 8000:8000
    volumes:
    - meerschaum_api_config_resources:${MEERSCHAUM_API_CONFIG_RESOURCES}
  meerschaum_db:
    environment:
    - TIMESCALEDB_TELEMETRY=off
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_DB=${POSTGRES_DB}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    hostname: ${MEERSCHAUM_DB_HOSTNAME}
    image: timescale/timescaledb:${TIMESCALEDB_VERSION}
    networks:
    - backend
    ports:
    - 5432:5432
    volumes:
    - meerschaum_db_data:/var/lib/postgresql/data
version: '3.8'
volumes:
  grafana_storage: null
  meerschaum_api_config_resources: null
  meerschaum_db_data: null
