[tool.poetry]
name = "dina-test"
version = "0.1.2"
description = ""
authors = ["dinabandhu50 <beheradinabandhu50@gmail.com>"]
license = "MIT"
readme = "README.rst"
exclude = ["docs/**/*"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.19.1"
sphinx = "^3.2.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = {version = "^19.10b0", allow-prereleases = true}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
