# Remember to run `poetry update` after you edit this file!

[tool.poetry]
    name = "rpgpack"
    version = "5.9.2"
    description = "A Dungeons & Dragons utilities pack for Royalnet"
    authors = ["Stefano Pigozzi <ste.pigozzi@gmail.com>"]
    license = "AGPL-3.0-or-later"
    readme = "README.md"
    homepage = "https://github.com/Steffo99/rpgpack"
    classifiers = [
        "Development Status :: 4 - Beta",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3.8",
        "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)"
    ]

# Library dependencies
[tool.poetry.dependencies]
    python = "^3.8"
    dice = "^2.4.2"
    sortedcontainers = "^2.1.0"
    aiohttp = "^3.5"

    # Required by poetry?!
    bcrypt = "3.2.0"
    sqlalchemy = "1.3.19"

    [tool.poetry.dependencies.royalnet]
        version = "~5.11.12"
        extras = [
            "alchemy_easy",
            "herald",
            "telegram",
            "discord",
            "constellation",
        ]

# Development dependencies
[tool.poetry.dev-dependencies]


# Optional dependencies
[tool.poetry.extras]


[build-system]
    requires = ["poetry>=0.12"]
    build-backend = "poetry.masonry.api"
