
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-18T05:10:12+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3f3cb6162a90238ea2a4f6589a02fa848f75c8ec",
 "version": "1.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
