# coding: utf-8

"""
    CloudCheckr API

    CloudCheckr API  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@cloudcheckr.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudcheckr_cmx
from cloudcheckr_cmx.models.permitted_child_customer_model import PermittedChildCustomerModel  # noqa: E501
from cloudcheckr_cmx.rest import ApiException


class TestPermittedChildCustomerModel(unittest.TestCase):
    """PermittedChildCustomerModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPermittedChildCustomerModel(self):
        """Test PermittedChildCustomerModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudcheckr_cmx.models.permitted_child_customer_model.PermittedChildCustomerModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
