[tool.poetry]
name = "mindustry"
version = "1.3.8"
description = "this library allows you to manage mindustry ------------------------------------ lib using PyAutoGUI Keyboard Mouse ----------------------------------- Command to install pip install mindustry"
authors = ["ASVI <aaaaaabbbbbbccscc@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
