root: false
cache: pip

language: python
python:
  - 3.7
stages:
  - lint
  - test
jobs:
  include:
    # lint stage
    - stage: lint
    - env: TOXENV=flake8
    # test stage
    - stage: test
      env: TOXENV=py
install:
  - sh -c 'if [ "$TOXENV" = "py" ]; then pip install tox codecov; else pip install tox; fi'
script:
  - tox
after_success:
  - sh -c 'if [ "$TOXENV" = "py" ]; then tox -e coverage-report; codecov; fi'