
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-15T15:16:19-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "528d48d6b07f4cdcf7cb116baf2140f5c789fea8",
 "version": "0.0.5a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
