[tool.poetry]
name = "basecone"
version = "0.1.11"
description = ""
authors = ["Pascal Prins <pascal.prins@foobar-it.com>"]
include = ["pyproject.toml"]

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.0"
requests = "^2.23.0"
pyyaml = "^5.3"
flask = "^1.1.2"
toml = "^0.10.1"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
autopep8 = "^1.5"
black = {version = "^19.10b0", allow-prereleases = true}

[tool.poetry.scripts]
basecone = "basecone.cli:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
