factories:
  model:
    ModelFactory: {}

  loss: 
    LossFactory: {}
                          
  miner: 
    MinerFactory: {}

  sampler:
    SamplerFactory: {}

  optimizer:
    OptimizerFactory: {}

  tester:
    TesterFactory: {}

  trainer:
    TrainerFactory: {}

  transform:
    TransformFactory: {}

  split_manager:
    SplitManagerFactory: {}

  record_keeper:
    RecordKeeperFactory: {}

  hook:
    HookFactory: {}

  aggregator:
    AggregatorFactory: {}

  ensemble:
    EnsembleFactory: {}