[tool.poetry]
name = "cognite-logger"
version = "0.5.1"
description = "Library for configuring logger"
authors = ["Erlend Vollset <erlend.vollset@cognite.com>"]

packages = [
    { include="cognite", from="." },
]

[tool.black]
line-length = 120
target_version = ['py37']
include = '\.py$'

[tool.isort]
line_length=120                # corresponds to -w  flag
multi_line_output=3            # corresponds to -m  flag
include_trailing_comma=true    # corresponds to -tc flag
skip_glob = '^((?!py$).)*$'    # this makes sort all Python files
known_third_party = ["pythonjsonlogger"]

[tool.poetry.dependencies]
python = "^3.5"
python-json-logger = "^0.1.8"

[tool.poetry.dev-dependencies]
isort = "^4.3"
pre-commit = "^1.18"
pytest = "^5.2"
pytest-cov = "^2.8"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
