
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-16T09:59:08+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d7d2993c13dee69c2eabc62035e92afdd57625bc",
 "version": "0.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
