
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-10T10:39:35-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "bd0da7cd85fd57cabaeb66dfaf64b0bf6067e5a4",
 "version": "0.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
