[tool.poetry]
name = "automailer"
version = "0.1.1"
description = ""
authors = ["Jacob Clarke <jacobclarke718@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
yagmail = "^0.13.237"
markdown2 = "^2.3.9"
python-frontmatter = "^0.5.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
automailer = 'automailer.__main__:main'
