[tool.poetry]
name = "inspy-logger"
version = "2.0.0-alpha.4"
description = "Colorable, scalable logger for CLI"
authors = ["Taylor-Jayde Blackstone <tayjaybabee@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6.3"
colorlog = "^4.2.1"
setuptools-autover = "^1.0.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
