# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Testing

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pre-setup Python dependencies
        run: |
          python -m pip install --upgrade pip
          # Explicitly install flake8 for linting
          pip install flake8

      - name: Lint the codebase
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends build-essential pkg-config liblz4-dev libhdf5-dev libhdf5-serial-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # Explicitly install pytest for test running
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build and install Python package
        run: |
          python setup.py bdist_wheel
          pip install $(python -c "import pathlib; print([x for x in pathlib.Path('dist').glob('*.whl')][0])")

      - name: Run unittests
        run: |
          pytest
