
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-16T23:11:34+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "775b28fb0a6b367c1bd21c7bcee065f002d02ba1",
 "version": "v3.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
