[tool.poetry]
name = "pyhackasm"
version = "0.1.1"
description = "Assembler for Hack ASM written in Python 3"
authors = ["Arslan <rslnkrmt2552@gmail.com>"]
license = "GPL-3.0+"
readme= "README.md"

[tool.poetry.dependencies]
python = "^3.6"
typer = {extras = ["all"], version = "^0.3.2"}

[tool.poetry.dev-dependencies]
pytest = "^6.0.2"
pytest-cov = "^2.10.1"
pylint = "^2.6.0"


[tool.poetry.scripts]
pyasm = "pyhackasm.cli:cli"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
