default_session_data_timeout: 0
deployment:
  apiGatewayId: aaluvn1b85
  endpoints:
    alexaApiEndpointUrlNotRecommendedToUse: https://aaluvn1b85.execute-api.eu-west-3.amazonaws.com/amazonAlexaV1
    googleAssistantApiEndointUrl: https://aaluvn1b85.execute-api.eu-west-3.amazonaws.com/googleAssistantDialogflowV1
    samsungBixbyApiEndointUrl: https://aaluvn1b85.execute-api.eu-west-3.amazonaws.com/samsungBixbyV1
    siriApiEndointUrl: https://aaluvn1b85.execute-api.eu-west-3.amazonaws.com/appleSiriV1
  handlerFunctionPath: app_generated.lambda_handler
  lambda_name: toto12
  s3_bucket_name: lebucketavecbenoit
messages:
  database_client: dynamodb
  dynamodb:
    region_name: eu-west-3
    table_name: app_notifications_messages
  use_database_dynamic_messages: true
plugins:
  activated_plugins:
  - OfficialAudioFilesInsteadOfText
  installed_plugins:
  - OfficialAudioFilesInsteadOfText
sessions_users_data:
  database_client: dynamodb
  dynamodb:
    region_name: eu-west-3
    table_name: app_notifications_users-data
