[tool.poetry]
name = "cognite-air-ds-util"
version = "0.3.7"
description = "Data science utilities used in the AIR project"
authors = ["cognite <support@cognite.com>"]

packages = [
    { include="cognite", from="." },
]

[tool.black]
line-length = 120
target_version = ['py36']
include = '\.py$'

[tool.isort]
line_length=120                # corresponds to -w  flag
multi_line_output=3            # corresponds to -m  flag
include_trailing_comma=true    # corresponds to -tc flag
skip_glob = '^((?!py$).)*$'    # this makes sort all Python files
known_third_party = ["numpy", "pandas", "pytest", "ruamel"]
[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = true
envlist = py37,py38

[testenv]
deps =
    pytest
    pytest-cov

commands =
    coverage run --source cognite -m pytest -v tests
    coverage xml
"""

[tool.poetry.dependencies]
python = "^3.7"
cognite-sdk-experimental = "^0"
cognite-sdk = "^2"
"ruamel.yaml" = "^0.16.10"
pandas = "^1.0.3"
numpy = "^1.18.4"

[tool.poetry.dev-dependencies]
isort = "^4.3.21"
pytest = "^5.4.2"
pytest-cov = "^2.8.1"
pre-commit = "2.1.1"
black = "^19.10b0"
mypy = "^0.770"
flake8 = "^3.8.1"
tox = "^3.15.0"
tox-pyenv = "^1.1.0"


[[tool.poetry.source]]
name = "snakepit"
url = "https://cognite.jfrog.io/cognite/api/pypi/snakepit/simple"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
