
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-16T09:34:36+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0bea55360e1f6089131e4227a5a31d2dcf8d5d59",
 "version": "0.4.1.post.dev17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
