
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-16T07:19:53-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "1a91cf200ff6ae27baeff170e47373b62e636a23",
 "version": "0.13.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
