
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-17T12:38:03-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "aa2d0be27c423bc755c00fb60d9a74276cff315c",
 "version": "2.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
