[tool.poetry]
name = "netz"
version = "0.1.2"
description = ""
authors = ["mjaquier <mjaquier@admin.xyz>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.1.2"
chardet = "^3.0.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^19.10b0"
coverage = "^5.2.1"
pytest-cov = "^2.10.1"
open-mock-file = "^1.0.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
