- job:
    name: python-zaqarclient-functional
    parent: legacy-dsvm-base
    run: playbooks/zaqarclient-dsvm-functional/run.yaml
    post-run: playbooks/zaqarclient-dsvm-functional/post.yaml
    timeout: 6000
    required-projects:
      - openstack/devstack-gate
      - openstack/python-zaqarclient
      - openstack/zaqar
      - openstack/zaqar-tempest-plugin
      - openstack/zaqar-ui

- project:
    templates:
      - check-requirements
      - openstack-lower-constraints-jobs
      - openstack-python3-ussuri-jobs
      - openstackclient-plugin-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - python-zaqarclient-functional
    gate:
      jobs:
        - python-zaqarclient-functional
