# Generated by Django 2.0.8 on 2018-08-27 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raceratings', '0004_auto_20180827_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racerating',
            name='incumbent',
        ),
    ]
