# Generated by Django 2.2.15 on 2020-08-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raceratings', '0010_cumulativegeneratortoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('task_id', models.CharField(max_length=75, unique=True)),
                ('record_type', models.SlugField(choices=[('cumulative-records', 'Cumulative winner records'), ('race-ratings', 'Race ratings')], default='cumulative-records', max_length=25)),
                ('status', models.SmallIntegerField(choices=[(-1, 'In progress'), (0, 'Success'), (1, 'Fail')], default=-1)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
