[tool.poetry]
name = "pysm3"
version = "3.3.0"
description = "PySM generates full-sky simulations of Galactic emissions in intensity and polarization relevant to CMB experiments"
authors = ["Andrea Zonca <code@andreazonca.com>"]
readme = "README.rst"
repository = "https://github.com/healpy/pysm"

[tool.poetry.dependencies]
python = "^3.6"
healpy = "^1.13.0"
numba = ">0.49.1"
toml = "^0.10.1"
astropy = "^4.0.1"
sphinx = {version = "^3.0.4", optional = true}
sphinx-astropy = {version = "^1.3", optional = true}
nbsphinx = {version = "^0.7.0", optional = true}
sphinx-math-dollar = {version = "^1.1.1", optional = true}
pandoc = {version = "^1.0.2", optional = true}
ipykernel = {version = "^5.3.0", optional = true}
numpy = "^1.17 || ^1.18"
pytest = {version = "^5.4.3", optional = true}
pytest-astropy = {version = "^0.8.0", optional = true}
mpi4py = {version = "^3.0.3", optional = true}
tox = {version = "^3.15.1", optional = true}
importlib_resources = {version = "^2.0.1", python = "3.6"}
importlib-metadata = {version = "^1.0", python = "<3.8"}

[tool.poetry.extras]
test = ["pytest", "pytest-astropy", "mpi4py", "tox"]
docs = ["sphinx", "sphinx-astropy", "nbsphinx", "sphinx-math-dollar", "pandoc", "ipykernel"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
