apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "signs"
spec:
  default:
    predictor:
      minReplicas: 1
      custom:
        container:
          image: seldonio/signs:0.0.3
          args:
            - --model_name
            - signs
            - --model_dir
            - ./model_signs/
            - --http_port
            - "8081"
      logger:
        mode: request
