apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: ad-signs
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - image: seldonio/signsad:0.0.3
        args:
        - --model_name
        - signsad
        - --storage_uri
        - ./ad_vae_signs/
        - --reply_url
        - http://message-dumper.default
