[tool.poetry]
name = "scrabbler"
version = "0.1.1"
description = "Scrabbler."
authors = ["Michal Hozza <mhozza@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
string_algorithms = "^0.5.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
scrabbler = 'scrabbler.scrabbler:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
