
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-17T14:02:24-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "476f3e04221ae89884a658ef18fc06c0546a2da4",
 "version": "v0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
