
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-11T03:21:22+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9423851fca4e0fe03ca287d85e4108c0c69b760b",
 "version": "1.13.0.post.dev100"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
