"""news model add

Revision ID: b1a7e861b22c
Revises: 62e733cd17d3
Create Date: 2020-09-01 17:59:01.792723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1a7e861b22c'
down_revision = '62e733cd17d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'news',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('site_id', sa.Integer(), nullable=True),
        sa.Column('title', sa.String(length=256), nullable=True),
        sa.Column('text', sa.Text(), nullable=True),
        sa.Column('text_hashed', sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    # ### end Alembic commands ###
