#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup


setup(name='tfreader',
      version='1.0.0',
      description='Whole-slide image file reader for TensorFlow',
      author='Lee Newberg',
      author_email='lee.newberg@kitware.com',
      url='https://github.com/DigitalSlideArchive/tensorflow_reader',
      py_modules=['tfreader'],
     )
