[tool.poetry]
name = "perip"
version = "0.1.0"
description = ""
authors = ["David J Barnes <david@onepointone.com>"]

[tool.poetry.dependencies]
python = "^3.8"
aosong = "^0.0.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
