language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -qr requirements-test.txt
script:
  - pytest --cov-report term-missing --cov=jsonrpc_websocket tests.py
notifications:
  email: false
after_success:
  coveralls
