on: push
name: Test
jobs:
  testWithTox:
    name: Test with tox
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: pip cache
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key:
          ${{ runner.os }}-pip-${{ hashFiles('**/setup.py')
          }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - run: pip install tox-conda
    - run: tox
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
