
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-15T09:47:31-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "bbd5e8868879022d15f188aa029c506a30897aa9",
 "version": "2.3.0dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
