[tool.poetry]
name = "smpw"
version = "1.0.0"
description = "my modile is python 3.8 is hack from windows 10 and my name is nick pl. lead the team  please pip install start"
authors = ["John Smith <azarovnick@bk.ru>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
