
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-15T13:20:15-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "d456b250326822b35169bbd52be5c143b6599fdc",
 "version": "0.49.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
