# Generated by Django 2.0.13 on 2019-12-30 12:25
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("webauthin", "0005_authdata_friendly_name")]

    operations = [
        migrations.RenameField(
            model_name="authdata", old_name="friendly_name", new_name="name"
        )
    ]
