[tool.poetry]
name = "appchen"
version = "0.3.2"
description = "A client/server web framework based on Python and modern JavaScript."
authors = ["Wolfgang Kühn"]
homepage = "https://github.com/decatur/app-chen"
repository = "https://github.com/decatur/app-chen"
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
flask = "^1.1"
pymongo = "^3.7"
sseclient = "^0.0.24"
requests  = "^2.18.0"
formchen = "^0.1.3"

[build-system]
requires = ["poetry"]
build-backend = "poetry.masonry.api"
# requires = ["setuptools >= 40.6.0", "wheel"]
# build-backend = "setuptools.build_meta"
