"""user model add

Revision ID: 564923304d28
Revises: 46885c39f167
Create Date: 2020-08-16 23:29:03.043493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564923304d28'
down_revision = '46885c39f167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('password_hashed', sa.String(length=64), nullable=False),
        sa.Column('username', sa.String(length=20), nullable=False),
        sa.Column('email', sa.String(length=32), nullable=False),
        sa.Column('is_staff', sa.Boolean(), server_default='f', nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
