[tool.poetry]
name = "pulpcore_releases"
version = "0.1.0-beta"
description = "Pulpcore - Releases & Compatibility"
authors = ["Fabricio Aguiar <fabricio.aguiar@gmail.com>"]
license = "GPL-2.0-or-later"
readme = "README.md"

[tool.poetry.scripts]
prc = "pulpcore_releases.prc:run"

[tool.poetry.dependencies]
python = ">=3.6"
aiohttp = "^3.6.2"
packaging = "^20.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
