site_name: napari-ndtiffs
site_description: napari plugin for nd tiff folders with OpenCl deskew
site_author: Talley Lambert

theme: readthedocs

repo_url: https://github.com/tlambert03/napari-ndtiffs

pages:
- Home: index.md
