
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-11T17:59:48-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "033923ad9577f0938bf017677783630e5c366b45",
 "version": "1.3.4-rc.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
