
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-12T10:26:10+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "fc3f06abe5c85b847864c094cbd30be1f0dbbcb8",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
