
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-18T01:37:32-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "e6c2e6f4f3465a0c61530119cfcf7f9ed4070d6c",
 "version": "0.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
