[tool.poetry]
name = "biopipen"
version = "0.0.1"
description = "A set of PyPPL processes for bioinformatics."
authors = ["pwwang <pwwang@pwwang.com>"]
license = "MIT"
include = [
	"biopipen/scripts/*/*",
	"biopipen/utils/*/*",
	"biopipen/reports/*/*",
	"biopipen/params.toml"
]
exclude = ["biopipen/**/*.pyc"]

[tool.poetry.dependencies]
python = "^3.6"
PyPPL = "3.*"
pyparam = "*"
diot = "*"
toml = "0.*"
pyppl_annotate = "*"
pyppl_export = "*"
pyppl_report = "*"
rich = "6.*"

[tool.poetry.scripts]
biopipen = 'biopipen.cli:main'
biopipen-abc = 'biopipen.cli.proxy:abc'

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
