[tool.poetry]
name = "aurcore"
version = "1.0.1"
description = "Aurcore!"
authors= ["Zenith <z@zenith.dev>"]

[tool.poetry.dependencies]
python = ">3.8"
loguru = "^0.5.2"


[tool.poetry.dev-dependencies]
pytest = "*"
pytest-asyncio = "*"
pytest-repeat = "*"
#pytest-catchlog = "^1.2.2"
pytest-lazy-fixture = "^0.6.3"
