[tool.poetry]
name = "scenic"
version = "1.1.0"
description = "The Scenic scenario description language."
authors = [
	"Daniel Fremont <dfremont@ucsc.edu>",
	"Tommaso Dreossi",
	"Shromona Ghosh",
	"Xiangyu Yue",
	"Alberto L. Sangiovanni-Vincentelli",
	"Sanjit A. Seshia"
]
maintainers = ["Daniel Fremont <dfremont@ucsc.edu>"]
readme = "README.md"
license = "BSD-3-Clause"
repository = "https://github.com/BerkeleyLearnVerify/Scenic"
documentation = "https://scenic-lang.readthedocs.io"
classifiers = [
	'Operating System :: OS Independent',
	'Development Status :: 4 - Beta',
]

[tool.poetry.dependencies]
python = "^3.6"
dotmap = "^1.3.13"
shapely = "^1.7.0"
pypoly2tri = "^0.0.3"
matplotlib = "^3.2.1"
scipy = "^1.4.1"
antlr4-python3-runtime = "~4.8"
opencv-python = "^4.2.0"
numpy = "^1.18.2"
pillow = "^7.1.1"
pynverse = "^0.1.4"

Polygon3 = {version = "^3.0.8", optional = true}

pyproj = {version = "^2.6.0", optional = true}

pytest-randomly = {version = "^3.2.1", optional = true}
pytest = {version = "^5.4.1", optional = true}
sphinx = {version = "^3.0.0", optional = true}
tox = {version = "^3.14.0", optional = true}
sphinx_rtd_theme = {version = "^0.4.3", optional = true}

[tool.poetry.extras]
gpc_triangulation = ["Polygon3"]
guideways = ["pyproj"]
dev = [
	"pytest-randomly",
	"pytest",
	"sphinx",
	"sphinx_rtd_theme",
	"tox",
	"pygments",
	"pyproj",	# for running guideways modules
]

[tool.poetry.plugins."pygments.lexers"]
scenic = "scenic.syntax.pygment:ScenicLexer"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
