# Generated by Django 3.1.1 on 2020-09-11 05:13

import balloon_block_editor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200911_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='test',
        ),
        migrations.AddField(
            model_name='test',
            name='content',
            field=balloon_block_editor.fields.BalloonBlockEditorField(default=''),
            preserve_default=False,
        ),
    ]
