[package]
name = "rjieba"
version = "0.1.0"
authors = ["messense <messense@icloud.com>"]
edition = "2018"
description = "jieba-rs Python binding"
license = "MIT"
repository = "https://github.com/messense/rjieba-py"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rjieba"
crate-type = ["cdylib"]

[dependencies]
jieba-rs = { version = "0.6.1", features = ["tfidf", "textrank"] }
pyo3 = { version = "0.12.0", features = ["extension-module"] }
