- project:
    templates:
      - openstack-python3-victoria-jobs
      - openstack-cover-jobs
      - publish-openstack-docs-pti
      - check-requirements
      - openstackclient-plugin-jobs
      - openstack-lower-constraints-jobs
