
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-14T17:04:01-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b5080ef4b3cb5613dcdeacec890db0652692ed38",
 "version": "1.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
