
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-13T10:58:50+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a7ac40c96d6e2af47102563d0478a2220e2a2ab7",
 "version": "5.24.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
