
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: src/python/arcor2_execution:arcor2_execution_dist

from setuptools import setup

setup(**{
    'author': 'Robo@FIT',
    'author_email': 'imaterna@fit.vut.cz',
    'classifiers': [
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'Topic :: Software Development :: Build Tools',
        'License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)',
        'Programming Language :: Python :: 3.8',
        'Natural Language :: English',
        'Topic :: Scientific/Engineering',
    ],
    'description': 'ARCOR2 - Augmented Reality Collaborative Robot.',
    'license': (
        'LGPL',
    ),
    'name': 'arcor2_execution',
    'version': '0.8.0rc1',
    'package_dir': {
        '': 'src',
    },
    'packages': (
        'arcor2_execution',
        'arcor2_execution.scripts',
    ),
    'namespace_packages': (
    ),
    'package_data': {
        'arcor2_execution': (
            'VERSION',
            'py.typed',
        ),
    },
    'install_requires': (
        'aiologger==0.5.0',
        'aiorun==2020.6.1',
        'arcor2==0.8.0rc1',
        'arcor2_execution_data==0.8.0rc1',
        'dataclasses-jsonschema[fast-validation]@ git+https://github.com/zdenekm/dataclasses-jsonschema.git@issue-126',
        'pydobot@ git+https://github.com/zdenekm/pydobot',
        'websockets==8.1',
    ),
    'entry_points': {
        'console_scripts': [
            'arcor2_execution=arcor2_execution.scripts.execution',
        ],
    },
})
