[tool.poetry]
name = "DDDRoller"
version = "1.1.0"
description = "Dungeon and Dragons Dice Roller"
authors = ["Sharlon Regales <you@example.com>"]
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.8"

pytest-cov = { version = "^2.9.0", optional = true }
flake8-isort = { version = "3.0.0", optional = true }  # https://github.com/gforcada/flake8-isort
isort = { version = "^4.3.20", optional = true }  # TODO: watch for isort 5.x.x support in flake8-isort
sphinx_rtd_theme = { version =  "^0.5.0", optional = true }
snregales = "^0.2.0"

[tool.poetry.dev-dependencies]
ipython = "^7.16.1"
black = { version = "^19", allow-prereleases = true }  # https://github.com/ambv/black
pre-commit-hooks = "^3.1.0"
pre-commit = "^2.6.0"


[tool.poetry.extras]
local = ["pytest-tldr", "pytest-cov", "flake8-isort", "isort", "sphinx_rtd_theme", "rstcheck"]
lint = ["flake8-isort", "isort"]
test = ["pytest-cov"]
docs = ["sphinx_rtd_theme", "rstcheck"]

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.py$'
exclude = '''
(
    /(
          \.eggs 
        | \.git 
        | build
        | dist
    )/
)
'''

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
