# See: https://pre-commit.com/

repos:
-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.7.0
    hooks:
    - id: reorder-python-imports
