[tool.poetry]
name = "kerdokustats"
version = "1.0.4.2"
description = "KerdokuBot Stats"
authors = ["Grey Cat"]

readme = 'README.md'

homepage = "https://kerdokuds.ml"

keywords = ['packaging', 'stas', 'ds', 'discord', 'kerdoku', 'kerdokustats', 'kerdokuds', 'kerdokubot', 'Grey Cat']

[tool.poetry.dependencies]
python = "^3.4 ^3.5 ^3.6 ^3.7 ^3.8"
requests = "^2.24.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
