trainer~SWAP~1:
  DeepAdversarialMetricLearning:


trainer~APPLY~2:
  g_alone_epochs: 0
  metric_alone_epochs: 0
  g_triplets_per_anchor: 100
  loss_weights:
    metric_loss: 1
    synth_loss: 0.1
    g_adv_loss: 0.1
    g_hard_loss: 0.1
    g_reg_loss: 0.1
