[tool.poetry]
name = "pd3f-flair"
version = "0.6.0.1"
description = "Flair's language models without unnecessary dependencies"
authors = ["Alan Akbik <alan.akbik@gmail.com>", "Johannes Filter <hi@jfilter.de>"]
license = "MIT"
readme = "README.md"
packages = [
    {include = "flair"}
]


[tool.poetry.dependencies]
python = ">=3.6"
torch = "*"
numpy = "*"
deprecated = "*"
requests = "*"
tqdm = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"


[tool.black]
line-length = 88
target-version = ['py36', 'py37']
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.pytest_cache
    | build
    | dist
  )/
)
'''
