name: Python daily test

on:
  schedule:
    - cron:  '0 3,13 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest black isort setuptools --upgrade
    - name: Lint
      run: |
        flake8 iseq
        black --check iseq
        isort --check-only iseq
    - name: Test
      run: |
        pip install -e .
        pytest iseq --runslow
