dist: trusty
language: python
jobs:
  include:
  - os: linux
    python: 3.8
    dist: xenial
    sudo: true
    env:
    - BUILD=PYPI
install:
- pip install -r requirements/dev.txt
- pip install flake8
script:
- flake8
deploy:
  skip_cleanup: true
  skip_existing: true
  provider: pypi
  user: __token__
  password:
    secure: N01wX+AKR6A5LZbpcGK+QRIunHurSq8kn/YC0+c8h31hS+LaliZXvGvBVAhAig0v6yRSTXz0j0cf3rcR+xCQozCI56diPpcmd0nLXd0L6XYifN5KbmkKW1x/CDnaIhWzLU6KTHR2KdZYPnLJMPwtH8NMWIF5ExFCyaZVsUeFfXYicV2gPAQW8J2R4uUvjGTJLreeO4f1IWKp0iN0euiQmA5BknOkXIuqjrojxIB/Vp6xZtA40xK8m2/+aaxewLHi7YbdMJ1/gkHMk47E4Lxqfc6AEXpQRWe2VguCxRGQEnQoc5QyijYZGZ52/mhosGGDFt+CrKzmmgMdGZCzVR71R1OV5WBQOX55juesm1MecinJJAyVUvP5fqt9MXXs0uSP18XKXqrlh99/z/GnZtPxalsHqSXyrBdd7/9EiaGcegbpRahhb0G5Jo1NdjKDqp+L2lHQLKMN8DhfatdL70VOJSOynwJPTq8/E0Qc247sEpB248Bz9MzU3f40RV4S925aOelo1cdRIDE6B2+ujdP7ttIsiQhc5zEL89N5N0nRGdd1yFjS2itw51FRQNXEn8Rno066RgLRX9P5H/9ximVZokA+h+kiJ+XtFlwrdk3xcnPFb7uavCF338aXMWeE6OzN7wBSbqXzFPTEJjo90VWE/x2x9LeBUdWlXTcgBhx31no=
  on:
    tags: true
    all_branches: true
    distributions: sdist
    condition: "$BUILD = PYPI"
    repo: cloudblue/product-sync
