[tool.poetry]
name = "polyquack-django"
version = "0.2"
description = "Django utilities for polyglots"
authors = ["Patryk Bratkowski <git@patryk.tech>"]
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://gitlab.com/patryk-media/polyquack-django"
documentation = "https://patryk-media.gitlab.io/polyquack-django/docs/"
keywords = ["polyglot", "i18n", "pluralization", "django"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: Django :: 3.1",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Communications",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Software Development :: Internationalization",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Text Processing :: Linguistic"
]

[tool.poetry.dependencies]
python = ">=3.6"
polyquack = ">=0.2,<0.3"
Django = ">=3.1,<4"

[tool.poetry.dev-dependencies]
pytest = "~5.3"
pytest-cov = "~2.8"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
