sudo: required
language: python
dist: xenial
python:
- '3.7'
install:
- python --version
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install -e .
- sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386
script:
- (cd tests && ./run_tests)
deploy:
  provider: pypi
  user: __token__
  password:
    secure: dIjxrjnwuoUn0DgofxpLQGYaTJAapYm2Q11L5oQbPfEe59nZ11mngNtusSboMNBpoAzXa5UxpcnbaDtgRD2y2MXFTGomDhU0x2nKE+3akwLmXmfQ7ZyE3m18HBSVGkZYQ92u1x+60eGx0pew9K6XaXj60ttHw3XaqVNXtNtqJvw0r9jj6PgbKYfNb+xZ8GrYIab9Po40FxpC0ISMsk4I/UpGLXNsGWXIOWya2LkjgXkZ3r2nDPoy4ROPRpDGAEBsP/nE7hbg+hS9l7TiY34sLbrak1fzBx4uQl2P7wN//hIsOwseLojsWvUfjcEnVaGhBSnrZWES76C62w0/r9UHi/hgDoFbw121BenNKuFqv18Xro3wOJYgk/7DdUwUaNewUfpHQ+AhtKkz6dBRt6dI0Cj/Kn/PzaiM+iQ4g5fBNb5MWiqs8XleJmv5AoCHCmeIixW3WgOzrEgDTgDI/BhwLsdgYBibSKCPVOvWTRTncVwSoiT3mPchJJQaARL+B4gyebj04WUMqQ2zylfQFXdeTmxoVDl2iNFfYo17kzsfBj3/ldAbdQbu0oPglwbU9olTQT0Jx0yPDcFz14fyYQaIvOhScof1hs5/BNhH2aLUL1axGKrpOTOWWCSEGhUP8KKRahycArJfHH5Ucm089SjS9fGAGDVG2eAdyh3Q3+o0ud8=
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION = 3.7"
  distributions: sdist bdist_wheel
  skip_existing: true
