
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-11T19:07:52+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "18c93a1e61fcade783bea8850d686dae4acf4075",
 "version": "0.9.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
