
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-16T16:13:28+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e94c80e1e24bcc3d714dcd71f0539057db1f7f31",
 "version": "0.5.0.post.dev6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
