
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-17T09:32:44+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "14e4599725c296a064ec1ad142a5cbdbc93dd300",
 "version": "0.5.0.post.dev11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
