[tool.poetry]
name = "summit"
version = "0.5.0"
description = "Tools for optimizing chemical processes"
authors = ["Kobi Felton <kobi.c.f@gmail.com>", "Jan Rittig"]
license = "MIT"
readme = 'README.rst'
repository = "https://github.com/sustainable-processes/summit"
homepage = "https://github.com/sustainable-processes/summit"
keywords = ["machine-learning", "chemistry", "reactions", "optimization", 
            "neural-networks", "drug-discovery", "bayesian-optimization",
            "nelder-mead", "snobfit", "gryffin", "TSEMO"]
include = ["summit/benchmarks/experimental_emulator/data/*.csv", 
           "summit/benchmarks/experimental_emulator/trained_models/BNN/*.json",
           "summit/benchmarks/experimental_emulator/trained_models/BNN/*.pt"]
exclude = ["summit/benchmarks/experimental_emulator/trained_models/BNN/*.png",
           "summit/benchmarks/experimental_emulator/data/*.xlsx"]

[tool.poetry.dependencies]
pandas = "^1.1.0"
python = "^3.6.1"
GPy = "^1.9"
numpy = "1.18.0"
pyrff = "^1.0.1"
SQSnobFit = "^0.4.3"
fastprogress = "^0.2.3"
ipywidgets = "^7.5.1"
matplotlib = "^3.2.2"
pymoo = "^0.4.1"
gpyopt = "^1.2.6"
neptune-client = {version= "^0.4.115", optional = true}
hiplot = {version= "^0.1.12", optional = true}
neptune-contrib = {extras = ["viz"], version = "^0.22.0", optional=true}
# gryffin = {git = "https://github.com/sustainable-processes/gryffin", rev = "0.1.1"}
tensorflow = "^2.2.0"
tensorflow-probability = "^0.10.1"
tensorflow-estimator = ">=2.2.0,<2.3.0"
torch = "^1.4.0"
blitz-bayesian-pytorch = "0.2.3"
paramiko = {version="^2.7.1", optional=true}    
# scp = {git = "https://github.com/jbardin/scp.py", rev = "v0.13.2", optional = true}

[tool.poetry.extras]
experiments = ["neptune-client", "hiplot", "neptune-contrib", "paramiko"]

[tool.poetry.dev-dependencies]
pytest = "^3.0"
ipdb = "^0.13.2"
rope = "^0.17.0"
sphinx = "^3.2.1"
nbsphinx = "^0.7.1"
sphinx-rtd-theme = "^0.5.0"
black = {version = "^20.8b1", allow-prereleases = true}

[build-system]
requires = ["poetry>=0.12"]
build-backendpoetry = "poetry.masonry.api"
