language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
  # PyPy versions
  - "pypy"
  - "pypy3"

install:
  - pip install .[test] codecov

script:
  - check-manifest
  - pytest --cov=rootfinding

after_success:
  - codecov