#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

install_requires = \
['virtualenv>=20.0.31', 'pthogen']

entry_points = \
{'pthogen': ['virtualenv_reproducible = virtualenv_reproducible:pth']}

setup(name='virtualenv-reproducible',
      version='0.1.0',
      description="ensure the virtualenv doesn't download new packages",
      author='Thomas Grainger',
      author_email='virtualenv-reproducible@graingert.co.uk',
      url='https://github.com/graingert/virtualenv_reproducible',
      py_modules=['virtualenv_reproducible'],
      install_requires=install_requires,
      entry_points=entry_points,
     )
