[tool.poetry]
name = "sqlalchemy-uuidstr"
version = "0.1.0"
description = ""
authors = ["Sherub Thakur <sherub.thakur@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
sqlalchemy = "^1.3.19"

[tool.poetry.dev-dependencies]
pytest = "^6.0.2"
psycopg2-binary = "^2.8.6"
pytest-cov = "^2.10.1"
pymysql = "^0.10.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
