# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


class Key(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    private_key = ... # type: typing___Text
    public_key = ... # type: typing___Text

    def __init__(self,
        *,
        private_key : typing___Optional[typing___Text] = None,
        public_key : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> Key: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"private_key",u"public_key"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"private_key",b"private_key",u"public_key",b"public_key"]) -> None: ...

class Peer(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    public_key = ... # type: typing___Text
    preshared_key = ... # type: builtin___bool
    endpoint = ... # type: typing___Text
    persistent_keepalive_interval = ... # type: builtin___int
    last_handshake_time = ... # type: builtin___float
    rx_bytes = ... # type: builtin___int
    tx_bytes = ... # type: builtin___int
    protocol_version = ... # type: builtin___int

    @property
    def allowed_ips(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[IP]: ...

    def __init__(self,
        *,
        public_key : typing___Optional[typing___Text] = None,
        preshared_key : typing___Optional[builtin___bool] = None,
        endpoint : typing___Optional[typing___Text] = None,
        persistent_keepalive_interval : typing___Optional[builtin___int] = None,
        last_handshake_time : typing___Optional[builtin___float] = None,
        rx_bytes : typing___Optional[builtin___int] = None,
        tx_bytes : typing___Optional[builtin___int] = None,
        protocol_version : typing___Optional[builtin___int] = None,
        allowed_ips : typing___Optional[typing___Iterable[IP]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> Peer: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"allowed_ips",u"endpoint",u"last_handshake_time",u"persistent_keepalive_interval",u"preshared_key",u"protocol_version",u"public_key",u"rx_bytes",u"tx_bytes"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"allowed_ips",b"allowed_ips",u"endpoint",b"endpoint",u"last_handshake_time",b"last_handshake_time",u"persistent_keepalive_interval",b"persistent_keepalive_interval",u"preshared_key",b"preshared_key",u"protocol_version",b"protocol_version",u"public_key",b"public_key",u"rx_bytes",b"rx_bytes",u"tx_bytes",b"tx_bytes"]) -> None: ...

class Peers(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def peers(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[Peer]: ...

    def __init__(self,
        *,
        peers : typing___Optional[typing___Iterable[Peer]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> Peers: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"peers"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"peers",b"peers"]) -> None: ...

class IP(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    ip = ... # type: typing___Text

    def __init__(self,
        *,
        ip : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> IP: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"ip"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"ip",b"ip"]) -> None: ...

class WireguardInterface(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    ifindex = ... # type: builtin___int
    ifname = ... # type: typing___Text
    public_key = ... # type: typing___Text
    listen_port = ... # type: builtin___int

    def __init__(self,
        *,
        ifindex : typing___Optional[builtin___int] = None,
        ifname : typing___Optional[typing___Text] = None,
        public_key : typing___Optional[typing___Text] = None,
        listen_port : typing___Optional[builtin___int] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> WireguardInterface: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"ifindex",u"ifname",u"listen_port",u"public_key"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"ifindex",b"ifindex",u"ifname",b"ifname",u"listen_port",b"listen_port",u"public_key",b"public_key"]) -> None: ...
