# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ctid_programmer/qt4/main_window.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1235, 960)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.common_group = QtGui.QGroupBox(self.centralwidget)
        self.common_group.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.common_group.sizePolicy().hasHeightForWidth())
        self.common_group.setSizePolicy(sizePolicy)
        self.common_group.setSizeIncrement(QtCore.QSize(0, 0))
        self.common_group.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.common_group.setObjectName(_fromUtf8("common_group"))
        self.gridLayout = QtGui.QGridLayout(self.common_group)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_23 = QtGui.QLabel(self.common_group)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout.addWidget(self.label_23, 7, 0, 1, 2)
        self.r_source_spinbox = QtGui.QSpinBox(self.common_group)
        self.r_source_spinbox.setMaximum(10000000)
        self.r_source_spinbox.setObjectName(_fromUtf8("r_source_spinbox"))
        self.gridLayout.addWidget(self.r_source_spinbox, 6, 2, 1, 1)
        self.chip_combo = QtGui.QComboBox(self.common_group)
        self.chip_combo.setObjectName(_fromUtf8("chip_combo"))
        self.chip_combo.addItem(_fromUtf8(""))
        self.chip_combo.addItem(_fromUtf8(""))
        self.chip_combo.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.chip_combo, 0, 2, 1, 1)
        self.auto_serial_checkbox = QtGui.QCheckBox(self.common_group)
        self.auto_serial_checkbox.setObjectName(_fromUtf8("auto_serial_checkbox"))
        self.gridLayout.addWidget(self.auto_serial_checkbox, 5, 2, 1, 1)
        self.serial_spinbox = QtGui.QSpinBox(self.common_group)
        self.serial_spinbox.setMaximum(16777215)
        self.serial_spinbox.setObjectName(_fromUtf8("serial_spinbox"))
        self.gridLayout.addWidget(self.serial_spinbox, 4, 2, 1, 1)
        self.sensor_type_combo = QtGui.QComboBox(self.common_group)
        self.sensor_type_combo.setEditable(False)
        self.sensor_type_combo.setObjectName(_fromUtf8("sensor_type_combo"))
        self.gridLayout.addWidget(self.sensor_type_combo, 2, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.common_group)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 2)
        self.label_9 = QtGui.QLabel(self.common_group)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 2)
        self.r_load_spinbox = QtGui.QSpinBox(self.common_group)
        self.r_load_spinbox.setMaximum(10000000)
        self.r_load_spinbox.setObjectName(_fromUtf8("r_load_spinbox"))
        self.gridLayout.addWidget(self.r_load_spinbox, 7, 2, 1, 1)
        self.mfg_combo = QtGui.QComboBox(self.common_group)
        self.mfg_combo.setObjectName(_fromUtf8("mfg_combo"))
        self.mfg_combo.addItem(_fromUtf8(""))
        self.mfg_combo.setItemText(0, _fromUtf8(""))
        self.gridLayout.addWidget(self.mfg_combo, 1, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.common_group)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.common_group)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 2)
        self.label_24 = QtGui.QLabel(self.common_group)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout.addWidget(self.label_24, 6, 0, 1, 2)
        self.label_5 = QtGui.QLabel(self.common_group)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 2)
        self.model_lineEdit = QtGui.QLineEdit(self.common_group)
        self.model_lineEdit.setObjectName(_fromUtf8("model_lineEdit"))
        self.gridLayout.addWidget(self.model_lineEdit, 3, 2, 1, 1)
        self.verticalLayout.addWidget(self.common_group)
        self.param_group = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.param_group.sizePolicy().hasHeightForWidth())
        self.param_group.setSizePolicy(sizePolicy)
        self.param_group.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.param_group.setFlat(False)
        self.param_group.setObjectName(_fromUtf8("param_group"))
        self.verticalLayout.addWidget(self.param_group)
        self.horizontalLayout_1 = QtGui.QHBoxLayout()
        self.horizontalLayout_1.setObjectName(_fromUtf8("horizontalLayout_1"))
        self.load_template_btn = QtGui.QPushButton(self.centralwidget)
        self.load_template_btn.setObjectName(_fromUtf8("load_template_btn"))
        self.horizontalLayout_1.addWidget(self.load_template_btn)
        self.save_template_btn = QtGui.QPushButton(self.centralwidget)
        self.save_template_btn.setObjectName(_fromUtf8("save_template_btn"))
        self.horizontalLayout_1.addWidget(self.save_template_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.read_btn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.read_btn.sizePolicy().hasHeightForWidth())
        self.read_btn.setSizePolicy(sizePolicy)
        self.read_btn.setObjectName(_fromUtf8("read_btn"))
        self.horizontalLayout_3.addWidget(self.read_btn)
        self.reprogram_after_cal_btn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reprogram_after_cal_btn.sizePolicy().hasHeightForWidth())
        self.reprogram_after_cal_btn.setSizePolicy(sizePolicy)
        self.reprogram_after_cal_btn.setObjectName(_fromUtf8("reprogram_after_cal_btn"))
        self.horizontalLayout_3.addWidget(self.reprogram_after_cal_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.program_btn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.program_btn.sizePolicy().hasHeightForWidth())
        self.program_btn.setSizePolicy(sizePolicy)
        self.program_btn.setObjectName(_fromUtf8("program_btn"))
        self.verticalLayout.addWidget(self.program_btn)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Sans Mono"))
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.plainTextEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.plainTextEdit.setStyleSheet(_fromUtf8("background-color: black; color: white"))
        self.plainTextEdit.setUndoRedoEnabled(False)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.horizontalLayout.addWidget(self.plainTextEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1235, 24))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_preferences = QtGui.QAction(MainWindow)
        self.action_preferences.setObjectName(_fromUtf8("action_preferences"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.menuEdit.addAction(self.actionPreferences)
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.chip_combo, self.mfg_combo)
        MainWindow.setTabOrder(self.mfg_combo, self.sensor_type_combo)
        MainWindow.setTabOrder(self.sensor_type_combo, self.serial_spinbox)
        MainWindow.setTabOrder(self.serial_spinbox, self.auto_serial_checkbox)
        MainWindow.setTabOrder(self.auto_serial_checkbox, self.r_source_spinbox)
        MainWindow.setTabOrder(self.r_source_spinbox, self.r_load_spinbox)
        MainWindow.setTabOrder(self.r_load_spinbox, self.load_template_btn)
        MainWindow.setTabOrder(self.load_template_btn, self.save_template_btn)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "CTid Programmer", None))
        self.label.setText(_translate("MainWindow", "CTid Programmer", None))
        self.common_group.setTitle(_translate("MainWindow", "Common Information", None))
        self.label_23.setText(_translate("MainWindow", "Test Load Impedance", None))
        self.r_source_spinbox.setSuffix(_translate("MainWindow", " Ω", None))
        self.chip_combo.setItemText(0, _translate("MainWindow", "Auto Detect", None))
        self.chip_combo.setItemText(1, _translate("MainWindow", "ATtiny9", None))
        self.chip_combo.setItemText(2, _translate("MainWindow", "ATtiny10", None))
        self.auto_serial_checkbox.setText(_translate("MainWindow", "Automatically Select Serial Number", None))
        self.label_10.setText(_translate("MainWindow", "Sensor Type", None))
        self.label_9.setText(_translate("MainWindow", "Serial Number", None))
        self.r_load_spinbox.setSuffix(_translate("MainWindow", " Ω", None))
        self.label_11.setText(_translate("MainWindow", "Microchip", None))
        self.label_3.setText(_translate("MainWindow", "Manufacturer", None))
        self.label_24.setText(_translate("MainWindow", "Sensor Impedance", None))
        self.label_5.setText(_translate("MainWindow", "Model Name", None))
        self.param_group.setTitle(_translate("MainWindow", "Sensor Parameters", None))
        self.load_template_btn.setText(_translate("MainWindow", "Load Template", None))
        self.save_template_btn.setText(_translate("MainWindow", "Save as Template", None))
        self.read_btn.setText(_translate("MainWindow", "Read", None))
        self.reprogram_after_cal_btn.setText(_translate("MainWindow", "Reprogram after Cal", None))
        self.program_btn.setText(_translate("MainWindow", "Program", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.action_preferences.setText(_translate("MainWindow", "Preferences", None))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences", None))
        self.actionPreferences.setShortcut(_translate("MainWindow", "Ctrl+P", None))

