[tool.poetry]
name = "minionize"
version = "0.1.7"
description = "Massively Parallel operations made easy"
authors = ["msimonin <matthieu.simonin@inria.fr>"]
license = "GPLv3"

readme = "README.rst"

repository = "https://gitlab.inria.fr/msimonin/minionize"

keywords = ["experimentation", "oar", "grid5000", "parallel"]

[tool.poetry.dependencies]
python = "^3.6"
execo = "^2.6.4"
google-cloud-pubsub = "^1.7.0"
python-dotenv = "^0.14.0"
pulsar-client = "^2.6.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^20.8b1"
mypy = "^0.782"
ipdb = "^0.13.3"
flake8 = "^3.8.3"
pytest-cov = "^2.10.1"
mock = "^4.0.2"
bump2version = "^1.0.0"

[tool.poetry.scripts]
minionize = 'minionize.cli:run'

[tool.black]
line-length = 88
target_version = ['py37']
include = '\.pyi?$'


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
