# Generated by Django 2.2.15 on 2020-08-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raceratings', '0009_auto_20191030_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='CumulativeGeneratorToken',
            fields=[
                ('uid', models.CharField(blank=True, editable=False, max_length=500)),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('key', models.CharField(blank=True, max_length=40, primary_key=True, serialize=False, verbose_name='API key')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
