
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-18T08:34:41+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8fae93054962133a6fb5e735b5c338d8ac78410a",
 "version": "v0.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
