# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-15 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0004_auto_20190213_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='from_email',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
