[tool.poetry]
name = "GE_custom_slack_renderer"
version = "0.1.1"
description = "Complement library to customize Great Expectations Slack notifications"
authors = ["Eli Pino <elisabet.pino@glovoapp.com>"]

[tool.poetry.dependencies]
python = "^3.7"
great_expectations = "^0.12.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
