[tool.poetry]
name = "arcane-googleads"
version = "0.3.0"
description = "Package description"
readme = "README.md"
authors = ["Arcane <product@arcane.run>"]
packages = [
    { include = "arcane" }
]

[tool.poetry.dependencies]
python = "^3.6"
arcane-core = "^1.0.3"
googleads = "24.0.0"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
