[tool.poetry]
name = "mf88-affilitest"
version = "0.1.6"
description = ""
authors = ["vutr <me@vutr.io>"]

[tool.poetry.dependencies]
python = "^3.7.5"
requests = "^2.24.0"

[tool.poetry.dev-dependencies]
httpx = "^0.14.3"
pytest = "^6.0.2"
pytest-asyncio = "^0.14.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
