[tool.poetry]
name = "qrcodecreator"
version = "1.0.0"
description = "A module for creating qr codes without any extra effort. It is based on the: qrcode module:\"https://pypi.org/project/qrcode/\" so it must be installed. Usage example: qrcoder(\"some text for the qrcode.\",\"example.png\")\"\"\" you can just write the name without format, it will be automatically saved as .jpg"
authors = ["Pavel Popov <p16.popov@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
