[tool.poetry]
name = "aiosqlembic"
version = "0.3.7"
description = "Migrations powered by aiosql"
authors = ["euri10 <benoit.barthelet@gmail.com>"]
license = "Unlicense"
readme = "README.md"
repository = "https://gitlab.com/euri10/aiosqlembic"
documentation = "https://aiosqlembic.readthedocs.io/en/latest/"
keywords = ["asyncpg", "postgresql", "migration"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Information Technology",
    "Intended Audience :: System Administrators",
    "License :: Public Domain",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: SQL",
    "Topic :: Database :: Front-Ends",
    "Topic :: Internet :: WWW/HTTP",
    "Typing :: Typed"
]

[tool.poetry.scripts]
aiosqlembic = "aiosqlembic.main:main"

[tool.poetry.dependencies]
python = "^3.7"
pydantic = "^1.6.1"
asyncpg = "^0.21.0"
jinja2 = "^2.11.2"
aiosql = "^3.1.2"
colorama = "^0.4.3"


[tool.poetry.dev-dependencies]
pytest = "^6.0.2"
ipython = "^7.18.1"
flake8 = "^3.8.3"
black = "^20.8b1"
mypy = "^0.782"
pytest-asyncio = "^0.14.0"
pytest-cov = "^2.10.1"
coverage = "^5.3"
sphinx_rtd_theme = "^0.5.0"
nest_asyncio = "^1.4.0"
sphinx = "^3.2.1"
sphinx-rtd-theme = "^0.5.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
