# coding: utf-8


import pprint
import re  # noqa: F401

import six


class EnterpriseBasic(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'path': 'str',
        'name': 'str',
        'url': 'str',
        'avatar_url': 'str'
    }

    attribute_map = {
        'id': 'id',
        'path': 'path',
        'name': 'name',
        'url': 'url',
        'avatar_url': 'avatar_url'
    }

    def __init__(self, id=None, path=None, name=None, url=None, avatar_url=None):  # noqa: E501
        """EnterpriseBasic - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._path = None
        self._name = None
        self._url = None
        self._avatar_url = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if path is not None:
            self.path = path
        if name is not None:
            self.name = name
        if url is not None:
            self.url = url
        if avatar_url is not None:
            self.avatar_url = avatar_url

    @property
    def id(self):
        """Gets the id of this EnterpriseBasic.  # noqa: E501


        :return: The id of this EnterpriseBasic.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this EnterpriseBasic.


        :param id: The id of this EnterpriseBasic.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def path(self):
        """Gets the path of this EnterpriseBasic.  # noqa: E501


        :return: The path of this EnterpriseBasic.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this EnterpriseBasic.


        :param path: The path of this EnterpriseBasic.  # noqa: E501
        :type: str
        """

        self._path = path

    @property
    def name(self):
        """Gets the name of this EnterpriseBasic.  # noqa: E501


        :return: The name of this EnterpriseBasic.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this EnterpriseBasic.


        :param name: The name of this EnterpriseBasic.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def url(self):
        """Gets the url of this EnterpriseBasic.  # noqa: E501


        :return: The url of this EnterpriseBasic.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this EnterpriseBasic.


        :param url: The url of this EnterpriseBasic.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def avatar_url(self):
        """Gets the avatar_url of this EnterpriseBasic.  # noqa: E501


        :return: The avatar_url of this EnterpriseBasic.  # noqa: E501
        :rtype: str
        """
        return self._avatar_url

    @avatar_url.setter
    def avatar_url(self, avatar_url):
        """Sets the avatar_url of this EnterpriseBasic.


        :param avatar_url: The avatar_url of this EnterpriseBasic.  # noqa: E501
        :type: str
        """

        self._avatar_url = avatar_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EnterpriseBasic, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EnterpriseBasic):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
