# coding: utf-8


import pprint
import re  # noqa: F401

import six


class NamespaceMini(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'type': 'str',
        'name': 'str',
        'path': 'str',
        'html_url': 'str'
    }

    attribute_map = {
        'id': 'id',
        'type': 'type',
        'name': 'name',
        'path': 'path',
        'html_url': 'html_url'
    }

    def __init__(self, id=None, type=None, name=None, path=None, html_url=None):  # noqa: E501
        """NamespaceMini - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._type = None
        self._name = None
        self._path = None
        self._html_url = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if type is not None:
            self.type = type
        if name is not None:
            self.name = name
        if path is not None:
            self.path = path
        if html_url is not None:
            self.html_url = html_url

    @property
    def id(self):
        """Gets the id of this NamespaceMini.  # noqa: E501


        :return: The id of this NamespaceMini.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this NamespaceMini.


        :param id: The id of this NamespaceMini.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def type(self):
        """Gets the type of this NamespaceMini.  # noqa: E501


        :return: The type of this NamespaceMini.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this NamespaceMini.


        :param type: The type of this NamespaceMini.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def name(self):
        """Gets the name of this NamespaceMini.  # noqa: E501


        :return: The name of this NamespaceMini.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this NamespaceMini.


        :param name: The name of this NamespaceMini.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def path(self):
        """Gets the path of this NamespaceMini.  # noqa: E501


        :return: The path of this NamespaceMini.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this NamespaceMini.


        :param path: The path of this NamespaceMini.  # noqa: E501
        :type: str
        """

        self._path = path

    @property
    def html_url(self):
        """Gets the html_url of this NamespaceMini.  # noqa: E501


        :return: The html_url of this NamespaceMini.  # noqa: E501
        :rtype: str
        """
        return self._html_url

    @html_url.setter
    def html_url(self, html_url):
        """Sets the html_url of this NamespaceMini.


        :param html_url: The html_url of this NamespaceMini.  # noqa: E501
        :type: str
        """

        self._html_url = html_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NamespaceMini, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NamespaceMini):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
