# coding: utf-8

"""
    CloudCheckr API

    CloudCheckr API  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@cloudcheckr.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudcheckr_cmx
from cloudcheckr_cmx.api.users_api import UsersApi  # noqa: E501
from cloudcheckr_cmx.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = cloudcheckr_cmx.api.users_api.UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_user(self):
        """Test case for create_user

        Create a new user.  # noqa: E501
        """
        pass

    def test_delete_user(self):
        """Test case for delete_user

        Delete a user.  # noqa: E501
        """
        pass

    def test_get_user(self):
        """Test case for get_user

        Get an individual user.  # noqa: E501
        """
        pass

    def test_list_users(self):
        """Test case for list_users

        Get all users.  # noqa: E501
        """
        pass

    def test_send_activation(self):
        """Test case for send_activation

        Send a user activation email.  # noqa: E501
        """
        pass

    def test_update_user(self):
        """Test case for update_user

        Update a user.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
