apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: ad-mnist
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - image: seldonio/mnistad:0.0.3
        args:
        - --model_name
        - mnistad
        - --storage_uri
        - ./ad_vae_mnist/
        - --reply_url
        - http://message-dumper.default
