apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: adversarial-mnist-trigger
  namespace: default
spec:
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: ad-mnist
      
