[tool.poetry]
name = "pedroai"
version = "0.1.10"
description = ""
authors = ["Pedro Rodriguez <me@pedro.ai>"]

[tool.poetry.dependencies]
python = "^3.7"
plotnine = "^0.7"
requests = "^2.23.0"
pysimdjson = {extras = ["dev"], version = "^2.4.0"}

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^19.10b0"
pylint = "^2.4.4"
mypy = "^0.782"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
