FORMULATION DIRECTORY: R:\RRP Technology & Product Research\Aerosol Research\Projects\CR Subject Nicotine Kinetics\Formulation table
RESULTS DIRECTORY: R:\RRP Technology & Product Research\Aerosol Research\Projects\CR Subject Nicotine Kinetics\Project Henry constant\Results
