[build-system]
requires = ["setuptools >= 35.0.2", "wheel >= 0.29.0", "poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "pyairnow"
version = "1.0.1"
description = "A lightweight Python wrapper for EPA AirNow Air Quality API"
readme = "README.md"
authors = ["Jonathan Krauss <jkrauss@asymworks.com>"]
license = "MIT"
repository = "https://github.com/asymworks/pyairnow"
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Topic :: Scientific/Engineering :: Atmospheric Science",
  "Topic :: Software Development :: Libraries",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Typing :: Typed",
]

[tool.poetry.dependencies]
aiohttp = "^3.6.2"
python = "^3.6"

[tool.poetry.dev-dependencies]
aioresponses = "^0.6.4"
coverage = "^5.2.1"
flake8 = "^3.8.3"
pytest = "^6.0.2"
pytest-asyncio = "^0.14.0"
pytest-cov = "^2.10.1"
