[tool.poetry]
name = "polyquack"
version = "0.2.4"
description = "utilities for polyglots"
authors = ["Patryk Bratkowski <git@patryk.tech>"]
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://gitlab.com/patryk-media/polyquack"
documentation = "https://patryk-media.gitlab.io/polyquack/docs/"
homepage = "https://patryk-media.gitlab.io/polyquack/"
keywords = ["polyglot", "i18n", "pluralization"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Communications",
    "Topic :: Software Development :: Internationalization",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Text Processing :: Linguistic"
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "~5.3"
pytest-cov = "~2.8"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
