service: sampleapp

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.7

functions:
  helloWorld:
    handler: hello_world.handler

package:
  exclude:
    - node_modules/**
    - package.json
    - package-lock.json
