[tool.poetry]
name = "powderbooking"
version = "0.4.3"
description = "RESTful API backend for the Powderbooking application"
license = "Apache-2.0"
authors = ["Michael Kemna <michael.kemna@gmail.com>"]
classifiers=[
          'Development Status :: 3 - Alpha',
          'License :: OSI Approved :: Apache Software License',
          'Programming Language :: Python :: 3.6',
          'Topic :: Database :: Database Engines/Servers',
      ]
include=["README.md", "LICENSE"]

[tool.poetry.dependencies]
python = "^3.7"
SQLalchemy = "^1.3.19"

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"
pytest-cov = "^2.10.1"
pytest-xdist = "^2.1.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
