[tool.poetry]
name = "beet"
version = "0.1.2"
description = "The Minecraft pack development kit"
authors = ["Valentin Berlier <berlier.v@gmail.com>"]
license = "MIT"

homepage = "https://github.com/vberlier/beet"
repository = "https://github.com/vberlier/beet"
documentation = "https://github.com/vberlier/beet"

readme = "README.md"

keywords = [
  "beet",
  "minecraft",
  "datapack",
  "resourcepack",
  "mcfunction"
]

[tool.poetry.dependencies]
python = "^3.8"
click = "^7.1.2"
click-help-colors = "^0.8"
nbtlib = "^1.8.0"
pathspec = "^0.8.0"
Pillow = "^7.2.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
pytest = "^6.0.1"
rope = "^0.17.0"
pytest-minecraft = "^0.1.0"
mypy = "^0.782"
pylint = "^2.6.0"

[tool.poetry.scripts]
beet = "beet.cli:main"

[tool.black]
target-version = ["py38"]
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
